siscostura/siscostura/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [

    # Inclui as URLs do app website
    path('', include('website.urls', namespace='website')),
    # Adminstrativo
    path("admin/", admin.site.urls),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

siscostura/website/urls.py
# Importamos a função index() definida no arquivo views.py
from django.urls import path
from django.urls import include
from . import views
from .views import delete_item
from django.contrib.auth import views as auth_views

app_name = 'website'

# urlpatterns contém a lista de roteamentos de URLs
urlpatterns = [

    # GET /
    path('', views.HomeView.as_view(), name="index"),

    # GET /clientes
    path('clientes/', views.HomeClienteView.as_view(),
         name="index_clientes"),

    # GET /clientes/cadastrar
    path('clientes/cadastrar', views.CriaClienteView.as_view(),
         name="cadastra_cliente"),

    # GET /clientes
    path('clientes/lista', views.ListaclientesView.as_view(),
         name="lista_clientes"),

    # GET/POST /clientes/{pk}
    path('clientes/<pk>', views.AtualizaClienteView.as_view(),
         name="atualiza_cliente"),

    # GET/POST /clientes/excluir/{pk}
    path('clientes/excluir/<pk>',
         views.DeletaClienteView.as_view(), name="deleta_cliente"),


    # GET /pedidos
    path('pedidos/', views.HomePedidoView.as_view(),
         name="index_pedidos"),

    # GET /pedidos/cadastrar
    path('pedidos/cadastrar', views.CriaPedidoView.as_view(),
         name="cadastra_pedido"),

    # GET /pedidos
    path('pedidos/lista', views.ListaPedidoView.as_view(),
         name="lista_pedidos"),

    # GET/POST /pedidos/{pk}
    path('pedidos/<pk>', views.AtualizaPedidoView.as_view(),
         name="atualiza_pedido"),

    # GET/POST /clientes/excluir/{pk}
    path('pedidos/excluir/<pk>',
         views.DeletaPedidoView.as_view(), name="deleta_pedido"),

    path('delete-item/<int:pk>/', delete_item, name='delete_item'),

    #path('add-row/', views.add_row_pedido_items_hx, name='add_row_pedido_items_hx'),
     


]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),    
]

siscostura/website/forms.py
from siscostura.models import Cliente
from siscostura.models import Pedido
from siscostura.models import ItemPedido
from django import forms
from django.forms import inlineformset_factory

# FORMULÁRIO DE INCLUSÃO DE CLIENTES
# -------------------------------------------

class InsereClienteForm(forms.ModelForm):

    observacao = forms.CharField(
        label='Observação',
        required=False,
        widget=forms.Textarea
    )

    data_nascimento = forms.DateField(
        label='Data nascimento',
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    ESTADOS = (('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'),
               ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'))
    endereco_estado = forms.ChoiceField(choices=ESTADOS)

    class Meta:
        # Modelo base
        model = Cliente

        # Campos que estarão no form
        fields = [
            'nome',
            'data_nascimento',
            'cpf',
            'telefone',
            'endereco_logradouro',
            'endereco_numero',
            'endereco_complemento',
            'endereco_cep',
            'endereco_bairro',
            'endereco_cidade',
            'endereco_estado',
            'observacao',
        ]

# FORMULÁRIO DE INCLUSÃO DE PEDIDOS
# -------------------------------------------


class InserePedidoForm(forms.ModelForm):

    observacao = forms.CharField(
        label='Observação',
        required=False,
        widget=forms.Textarea
    )

    cliente = forms.ModelChoiceField(
        label='Cliente',        
        queryset=Cliente.objetos.all().order_by('nome'),
        required=True,
        
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    data_pedido = forms.DateField(
        label='Data pedido',
        required=False,
        widget=forms.DateInput(format='%d/%m/%Y')
    )

    class Meta:
        # Modelo base
        model = Pedido

        fields = '__all__'

class ItemPedidoForm(forms.ModelForm):
    class Meta:
        model = ItemPedido
        fields = '__all__'

ItemPedidoFormSet = inlineformset_factory(
    Pedido, ItemPedido, form=ItemPedidoForm,
    extra=1, can_delete=True,
    can_delete_extra=True
)

siscostura/website/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from siscostura.models import Cliente
from siscostura.models import Pedido
from .forms import InserePedidoForm
from django.urls import reverse_lazy
from .forms import InsereClienteForm
from django.urls import reverse_lazy
from .forms import ItemPedidoFormSet
from .forms import ItemPedidoForm
from siscostura.models import ItemPedido
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


# Create your views here.


# PÁGINA PRINCIPAL
# ----------------------------------------------


@method_decorator(login_required(login_url='accounts/login/'), name='dispatch')
class HomeView(TemplateView):
    template_name = "website/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data()

        return context


# PÁGINA PRINCIPAL CLIENTES
# ----------------------------------------------

class HomeClienteView(TemplateView):
    template_name = "website/clientes/index.html"


# LISTA DE CLIENTES
# ----------------------------------------------

class ListaclientesView(ListView):
    template_name = "website/clientes/lista.html"
    model = Cliente
    context_object_name = "clientes"


    def get_queryset(self):
        queryset = super().get_queryset()
        term = self.request.GET.get('search')

        print(term)
        if term:
            return queryset.filter(nome__icontains=term)
        return queryset


# CADASTRAMENTO DE CLIENTES
# ----------------------------------------------

class CriaClienteView(CreateView):
    template_name = "website/clientes/cria.html"
    model = Cliente
    form_class = InsereClienteForm
    success_url = reverse_lazy("website:lista_clientes")


# ATUALIZAÇÃO DE CLIENTES
# ----------------------------------------------

class AtualizaClienteView(UpdateView):
    template_name = "website/clientes/atualiza.html"
    model = Cliente
    fields = '__all__'
    context_object_name = 'Cliente'
    success_url = reverse_lazy("website:lista_clientes")


# EXCLUSÃO DE CLIENTES
# ----------------------------------------------

class DeletaClienteView(DeleteView):
    template_name = "website/clientes/exclui.html"
    model = Cliente
    context_object_name = 'Cliente'
    success_url = reverse_lazy("website:lista_clientes")


# PÁGINA PRINCIPAL PEDIDOS
# ----------------------------------------------

class HomePedidoView(TemplateView):
    template_name = "website/pedidos/index.html"

# LISTA DE PEDIDOS
# ----------------------------------------------


class ListaPedidoView(ListView):
    template_name = "website/pedidos/lista.html"
    model = Pedido
    context_object_name = "pedidos"


# CADASTRAMENTO DE PEDIDOS
# ----------------------------------------------
class PedidoInline():
    form_class = InserePedidoForm
    model = Pedido
    template_name = "website/pedidos/cria.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        self.object = form.save()
        

        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_items_pedido_valid', None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('/pedidos/lista')

    def formset_items_pedido_valid(self, formset):
        """
        Hook for custom formset saving.. useful if you have multiple formsets
        """
        items_pedido = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this, if you have can_delete=True parameter set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for item_pedido in items_pedido:
            item_pedido.pedido = self.object
            item_pedido.save()


class CriaPedidoView(PedidoInline,CreateView):
     
    def get_context_data(self, **kwargs):
        ctx = super(CriaPedidoView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'item_pedido': ItemPedidoFormSet(prefix='items'),                
            }
        else:
            return {
                'item_pedido': ItemPedidoFormSet(self.request.POST or None, self.request.FILES or None, prefix='items'),                
            }




# ATUALIZAÇÃO DE PEDIDOS
# ----------------------------------------------

class AtualizaPedidoView(PedidoInline,UpdateView):
   def get_context_data(self, **kwargs):
        ctx = super(AtualizaPedidoView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx
   
   def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'items': ItemPedidoFormSet(prefix='items'),   
            }
        else:
            return {
                'items': ItemPedidoFormSet(self.request.POST or None, self.request.FILES or None, prefix='items'),                
            }


# EXCLUSÃO DE PEDIDOS
# ----------------------------------------------

class DeletaPedidoView(DeleteView):
    template_name = "website/pedidos/exclui.html"
    model = Pedido
    context_object_name = 'Pedido'
    success_url = reverse_lazy("website:lista_pedidos")

def delete_item(request, pk):
    try:
        itemPedido = ItemPedido.objetos.get(id=pk)
    except ItemPedido.DoesNotExist:
        messages.success(
            request, 'Objeto não encontrado'
            )
        return redirect('website:atualiza_pedido', pk=itemPedido.pedido.id)

siscostura/website/templates/website/pedidos/atualiza_old.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}
{% load static %}

{% block title %}Cadastro de Pedidos{% endblock %}

{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Consultar/Atualizar de Pedido</h5>                       
                        <form method="post">
                            <!-- Não se esqueça dessa tag -->
                            {% csrf_token %}

                            <!-- Nome -->
                                                        
                            {% for field in form %}
                                <div class="input-group mb-3">
                                    
                                    <span class="input-group-text">{{field.label}}
                                        {% if field.field.required %}
                                            <span style="color: red;" class="required">*</span>
                                        {% endif %}
                                    </span>                                    
                                    {% render_field field  class+="form-control" %}
                                    
                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p style="color: red">{{ error }}</p>
                                        </div>
                                    {% endfor %}
                                </div>                                
                            {% endfor %}

                            {{ formset.management_form }}                  
                          


                            {{ formset.management_form }}
                            <script type="text/html" id="items-template">  // id="inlineformsetname-template"
                                // id='inlineformsetname-__prefix__' 
                                <tr id="items-__prefix__" class= hide_all>
                                    {% for fields in formset.empty_form.hidden_fields %}
                                        {{ fields }}
                                    {% endfor %}
                                
                                    {% for fields in formset.empty_form.visible_fields %}
                                        <td>{{fields}}</td>
                                    {% endfor %}
                                </tr>
                            </script>
                            <div class="table-responsive card mt-4">
                                <div class="card-header card-header-secondary">
                                    <h4 class="card-title">Adicionar Itens</h4>
                                </div>
                                <table class="table card-header">
                                    <thead class="text-secondary">
                                        <th>Descrição <span style="color: red;" class="required">*</span></th>
                                        <th>Preço <span style="color: red;" class="required">*</span></th>
                                        <th>Cancelado <span style="color: red;" class="required">*</span></th>
                                        <th>Observação</th>
                                        <th>Ações</th>
                                    </thead>
                                    <tbody id="item-items">  <!-- id="item-inlineformsetname" -->
                                        <!-- formset non forms errors -->
                                        {% for error in formset.non_form_errors %}
                                            <span style="color: red">{{ error }}</span>
                                        {% endfor %}
                                        {% for formss in formset %}
                                            {{ formss.management_form }}
                                            <tr id="items-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                                                {{ formss.id }}
                                                {% for field in formss.visible_fields %}
                                                    <td>
                                                        {{field}}
                                                        {% for error in field.errors %}
                                                            <span style="color: red">{{ error }}</span>
                                                        {% endfor %}
                                                        
                                                        {% comment %} {{ field.DELETE }} {% endcomment %}
                                                    </td>
                                                {% endfor %}
                                                {% comment %} for delete {% endcomment %}
                                                {% if formss.instance.pk %}
                                                    <td>
                                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{formss.instance.pk}}">
                                                            Apagar
                                                        </button>
                                                        <!-- Modal -->
                                                        <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                                            <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">Você tem certeza que deseja apagar o item?</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                                </div>
                                                                <div class="modal-footer">
                                                                <a href="{% url 'website:delete_item' formss.instance.pk %}" class="btn btn-danger">Apagar</a>
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                                                </div>
                                                            </div>
                                                            </div>
                                                        </div>
                                                    </td>            
                                                {% endif %}
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <a href="#" id="add-item-button" class="btn btn-secondary add-items">Mais Itens</a> <!-- id="add-inlineformsetname-button" -->
                            </div>



                            <hr>
                            <div class="text-end">
                                <a href="{% url 'website:lista_pedidos' %}" class="btn btn-outline-primary">Voltar</a>
                                <button class="btn btn-primary">Enviar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script>
    $(document).ready(function() {
        // when user clicks add more btn of images
      $('.add-images').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-images').children().length;
          var tmplMarkup = $('#images-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-images').append(compiledTmpl);
  
          // update form count
          $('#id_images-TOTAL_FORMS').attr('value', count+1);
      });
  });

  $(document).ready(function() {
    // when user clicks add more btn of items
      $('.add-items').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-items').children().length;
          var tmplMarkup = $('#items-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-items').append(compiledTmpl);
  
          // update form count
          $('#id_items-TOTAL_FORMS').attr('value', count+1);
      });
  });
</script>
{% endblock %}

siscostura/website/templates/website/pedidos/exclui.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Exclusão de Cliente</h5>

                <p class="card-text">
                    Você tem certeza que quer excluir o pedido <b>{{ pedido.nome }}</b>?
                </p>

                <form method="post">
                    {% csrf_token %}

                    <hr/>
                    <div class="text-end">
                        <a href="{% url 'website:lista_pedidos' %}" class="btn btn-outline-danger">
                            Cancelar
                        </a>
                        <button class="btn btn-danger">Excluir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

siscostura/website/templates/website/pedidos/index.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cadastrar Pedido</h5>
                        <p class="card-text">
                            Cadastre aqui um novo <code>Pedido</code>.
                        </p>
                        <a href="{% url 'website:cadastra_pedido' %}"
                           class="btn btn-primary">
                            Novo Pedido
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Lista de Pedidos</h5>
                        <p class="card-text">
                            Veja aqui a lista de <code>Pedidos</code> cadastrados.
                        </p>
                        <a href="{% url 'website:lista_pedidos' %}"
                           class="btn btn-primary">
                            Vá para Lista
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

siscostura/website/templates/website/pedidos/lista.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Pedidos{% endblock %}


{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card border-dark" data-aos="fade-in" data-aos-duration="750">
                <div class="card-header"><b>Lista de Pedidos</b></div>
                    <div class="card-body">
                        {% if pedidos|length > 0 %}
                            <p class="card-text">Aqui está a lista de <code>Pedidos</code> cadastrados.</p>

                            <table class="table table-light table-striped table-hover align-middle">
                                <thead>
                                <tr>
                                    <th scope="col">Pedido</th>
                                    <th scope="col">Cliente</th>
                                    <th scope="col">Data pedido</th>
                                    <th scope="col">Status pedido</th>
                                    <th scope="col">Valor</th>
                                    <th scope="col" class="text-center">Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for pedido in pedidos %}
                                    <tr> 
                                        <td>{{ pedido.id }}</td>                                       
                                        <td>{{ pedido.cliente.nome }}</td>
                                        <td>{{ pedido.data_pedido }}</td>
                                        <td>{{ pedido.statusPedido.descricao }}</td>
                                        <td>{{ pedido.valor_total }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'website:atualiza_pedido' pk=pedido.id %}"
                                               class="btn btn-primary btn-sm">
                                                Atualizar
                                            </a>
                                            <a href="{% url 'website:deleta_pedido' pk=pedido.id %}"
                                               class="btn btn-danger btn-sm">
                                                Excluir
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <div class="text-center mt-5 mb-5 jumbotron">
                                <h5>Nenhum <code>Pedido</code> cadastrado ainda.</h5>
                            </div>
                        {% endif %}
                        <hr/>
                        <div class="text-end">
                            <a href="{% url 'website:cadastra_pedido' %}" class="btn btn-primary btn-sm">
                                Cadastrar Pedido
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}