siscostura/siscostura/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [

    # Inclui as URLs do app website
    path('', include('website.urls', namespace='website')),
    # Adminstrativo
    path("admin/", admin.site.urls),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

siscostura/website/urls.py
# Importamos a função index() definida no arquivo views.py
from django.urls import path
from django.urls import include
from . import views
from .views import delete_item
from django.contrib.auth import views as auth_views

app_name = 'website'

# urlpatterns contém a lista de roteamentos de URLs
urlpatterns = [

    # GET /
    path('', views.HomeView.as_view(), name="index"),

    # GET /clientes
    path('clientes/', views.HomeClienteView.as_view(),
         name="index_clientes"),

    # GET /clientes/cadastrar
    path('clientes/cadastrar', views.CriaClienteView.as_view(),
         name="cadastra_cliente"),

    # GET /clientes
    path('clientes/lista', views.ListaclientesView.as_view(),
         name="lista_clientes"),

    # GET/POST /clientes/{pk}
    path('clientes/<pk>', views.AtualizaClienteView.as_view(),
         name="atualiza_cliente"),

    # GET/POST /clientes/excluir/{pk}
    path('clientes/excluir/<pk>',
         views.DeletaClienteView.as_view(), name="deleta_cliente"),


    # GET /pedidos
    path('pedidos/', views.HomePedidoView.as_view(),
         name="index_pedidos"),

    # GET /pedidos/cadastrar
    path('pedidos/cadastrar', views.CriaPedidoView.as_view(),
         name="cadastra_pedido"),

    # GET /pedidos
    path('pedidos/lista', views.ListaPedidoView.as_view(),
         name="lista_pedidos"),

    # GET/POST /pedidos/{pk}
    path('pedidos/<pk>', views.AtualizaPedidoView.as_view(),
         name="atualiza_pedido"),

    # GET/POST /clientes/excluir/{pk}
    path('pedidos/excluir/<pk>',
         views.DeletaPedidoView.as_view(), name="deleta_pedido"),

    path('delete-item/<int:pk>/', delete_item, name='delete_item'),

    #path('add-row/', views.add_row_pedido_items_hx, name='add_row_pedido_items_hx'),
     


]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),    
]

siscostura/website/forms.py
from siscostura.models import Cliente
from siscostura.models import Pedido
from siscostura.models import ItemPedido
from django import forms
from django.forms import inlineformset_factory

# FORMULÁRIO DE INCLUSÃO DE CLIENTES
# -------------------------------------------

class InsereClienteForm(forms.ModelForm):

    observacao = forms.CharField(
        label='Observação',
        required=False,
        widget=forms.Textarea
    )

    data_nascimento = forms.DateField(
        label='Data nascimento',
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    ESTADOS = (('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'),
               ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'))
    endereco_estado = forms.ChoiceField(choices=ESTADOS)

    class Meta:
        # Modelo base
        model = Cliente

        # Campos que estarão no form
        fields = [
            'nome',
            'data_nascimento',
            'cpf',
            'telefone',
            'endereco_logradouro',
            'endereco_numero',
            'endereco_complemento',
            'endereco_cep',
            'endereco_bairro',
            'endereco_cidade',
            'endereco_estado',
            'observacao',
        ]

# FORMULÁRIO DE INCLUSÃO DE PEDIDOS
# -------------------------------------------


class InserePedidoForm(forms.ModelForm):

    observacao = forms.CharField(
        label='Observação',
        required=False,
        widget=forms.Textarea
    )

    cliente = forms.ModelChoiceField(
        label='Cliente',        
        queryset=Cliente.objetos.all().order_by('nome'),
        required=True,
        
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    data_pedido = forms.DateField(
        label='Data pedido',
        required=False,
        widget=forms.DateInput(format='%d/%m/%Y')
    )

    class Meta:
        # Modelo base
        model = Pedido

        fields = '__all__'

class ItemPedidoForm(forms.ModelForm):
    class Meta:
        model = ItemPedido
        fields = '__all__'

ItemPedidoFormSet = inlineformset_factory(
    Pedido, ItemPedido, form=ItemPedidoForm,
    extra=1, can_delete=True,
    can_delete_extra=True
)

siscostura/website/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from siscostura.models import Cliente
from siscostura.models import Pedido
from .forms import InserePedidoForm
from django.urls import reverse_lazy
from .forms import InsereClienteForm
from django.urls import reverse_lazy
from .forms import ItemPedidoFormSet
from .forms import ItemPedidoForm
from siscostura.models import ItemPedido
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


# Create your views here.


# PÁGINA PRINCIPAL
# ----------------------------------------------


@method_decorator(login_required(login_url='accounts/login/'), name='dispatch')
class HomeView(TemplateView):
    template_name = "website/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data()

        return context


# PÁGINA PRINCIPAL CLIENTES
# ----------------------------------------------

class HomeClienteView(TemplateView):
    template_name = "website/clientes/index.html"


# LISTA DE CLIENTES
# ----------------------------------------------

class ListaclientesView(ListView):
    template_name = "website/clientes/lista.html"
    model = Cliente
    context_object_name = "clientes"


    def get_queryset(self):
        queryset = super().get_queryset()
        term = self.request.GET.get('search')

        print(term)
        if term:
            return queryset.filter(nome__icontains=term)
        return queryset


# CADASTRAMENTO DE CLIENTES
# ----------------------------------------------

class CriaClienteView(CreateView):
    template_name = "website/clientes/cria.html"
    model = Cliente
    form_class = InsereClienteForm
    success_url = reverse_lazy("website:lista_clientes")


# ATUALIZAÇÃO DE CLIENTES
# ----------------------------------------------

class AtualizaClienteView(UpdateView):
    template_name = "website/clientes/atualiza.html"
    model = Cliente
    fields = '__all__'
    context_object_name = 'Cliente'
    success_url = reverse_lazy("website:lista_clientes")


# EXCLUSÃO DE CLIENTES
# ----------------------------------------------

class DeletaClienteView(DeleteView):
    template_name = "website/clientes/exclui.html"
    model = Cliente
    context_object_name = 'Cliente'
    success_url = reverse_lazy("website:lista_clientes")


# PÁGINA PRINCIPAL PEDIDOS
# ----------------------------------------------

class HomePedidoView(TemplateView):
    template_name = "website/pedidos/index.html"

# LISTA DE PEDIDOS
# ----------------------------------------------


class ListaPedidoView(ListView):
    template_name = "website/pedidos/lista.html"
    model = Pedido
    context_object_name = "pedidos"


# CADASTRAMENTO DE PEDIDOS
# ----------------------------------------------
class PedidoInline():
    form_class = InserePedidoForm
    model = Pedido
    template_name = "website/pedidos/cria.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        self.object = form.save()
        

        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_items_pedido_valid', None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('/pedidos/lista')

    def formset_items_pedido_valid(self, formset):
        """
        Hook for custom formset saving.. useful if you have multiple formsets
        """
        items_pedido = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this, if you have can_delete=True parameter set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for item_pedido in items_pedido:
            item_pedido.pedido = self.object
            item_pedido.save()


class CriaPedidoView(PedidoInline,CreateView):
     
    def get_context_data(self, **kwargs):
        ctx = super(CriaPedidoView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'item_pedido': ItemPedidoFormSet(prefix='items'),                
            }
        else:
            return {
                'item_pedido': ItemPedidoFormSet(self.request.POST or None, self.request.FILES or None, prefix='items'),                
            }




# ATUALIZAÇÃO DE PEDIDOS
# ----------------------------------------------

class AtualizaPedidoView(PedidoInline,UpdateView):
   def get_context_data(self, **kwargs):
        ctx = super(AtualizaPedidoView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx
   
   def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'items': ItemPedidoFormSet(prefix='items'),   
            }
        else:
            return {
                'items': ItemPedidoFormSet(self.request.POST or None, self.request.FILES or None, prefix='items'),                
            }


# EXCLUSÃO DE PEDIDOS
# ----------------------------------------------

class DeletaPedidoView(DeleteView):
    template_name = "website/pedidos/exclui.html"
    model = Pedido
    context_object_name = 'Pedido'
    success_url = reverse_lazy("website:lista_pedidos")

def delete_item(request, pk):
    try:
        itemPedido = ItemPedido.objetos.get(id=pk)
    except ItemPedido.DoesNotExist:
        messages.success(
            request, 'Objeto não encontrado'
            )
        return redirect('website:atualiza_pedido', pk=itemPedido.pedido.id)

siscostura/website/templates/website/clientes/atualiza.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Clientes{% endblock %}

{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Atualizar Dados de Clientes</h5>
                        <form method="post">
                            <!-- Não se esqueça dessa tag -->
                            {% csrf_token %}

                             <!-- Nome -->
                             <div class="input-group mb-3">
                                <span class="input-group-text">Nome</span>
                                {% render_field form.nome class+="form-control" %}
                            </div>
                                                   
                           
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <!-- CPF -->
                                    <div class="input-group mb-3">
                                        <span class="input-group-text">CPF</span>
                                        {% render_field form.cpf class+="form-control" %}
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <!-- data_nascimento -->
                                    <div class="input-group mb-3">
                                        <span class="input-group-text">Data nascimento</span>
                                        {% render_field form.data_nascimento class+="form-control" %}
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                    <!-- telefone -->
                                    <div class="input-group mb-3">
                                        <span class="input-group-text">Telefone</span>
                                        {% render_field form.telefone class+="form-control" %}
                                    </div>
                                </div>
                            </div>
                          
                            <fieldset class="border p-2">
                                <legend>Endereço</legend>
                                <div class="row">
                                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                                        
                                        <!-- endereco_logradouro -->
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">Rua/Av.:</span>
                                            {% render_field form.endereco_logradouro class+="form-control" %}
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                        <!-- endereco_numero -->
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">Número</span>
                                            {% render_field form.endereco_numero class+="form-control" %}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                        <!-- endereco_complemento -->
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">Complemento</span>
                                            {% render_field form.endereco_complemento class+="form-control" %}
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                         <!-- endereco_cep -->
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">CEP</span>
                                            {% render_field form.endereco_cep class+="form-control" %}
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                         <!-- endereco_bairro -->
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">Bairro</span>
                                            {% render_field form.endereco_bairro class+="form-control" %}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                        <!-- endereco_cidade -->
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">Cidade</span>
                                            {% render_field form.endereco_cidade class+="form-control" %}
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                        <!-- endereco_estado -->
                                        <div class="input-group mb-3">
                                            <span class="input-group-text">Estado</span>
                                            {% render_field form.endereco_estado class+="form-control" %}
                                        </div>
                                    </div>
                                </div>                         
                            </fieldset>
                             

                            <!-- observacao -->
                            <div class="input-group mb-3">
                                <span class="input-group-text">Observação</span>
                                {% render_field form.observacao class+="form-control" %}
                            </div>
                            <hr>
                            
                            <hr/>
                            <div class="text-end">
                                <a href="{% url 'website:lista_clientes' %}" class="btn btn-outline-primary">Voltar</a>
                                <button class="btn btn-primary">Enviar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

siscostura/website/templates/website/clientes/exclui.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Exclusão de Cliente</h5>

                <p class="card-text">
                    Você tem certeza que quer excluir o cliente <b>{{ cliente.nome }}</b>?
                </p>

                <form method="post">
                    {% csrf_token %}

                    <hr/>
                    <div class="text-end">
                        <a href="{% url 'website:lista_clientes' %}" class="btn btn-outline-danger">
                            Cancelar
                        </a>
                        <button class="btn btn-danger">Excluir</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

siscostura/website/templates/website/clientes/index.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cadastrar Cliente</h5>
                        <p class="card-text">
                            Cadastre aqui um novo <code>Cliente</code>.
                        </p>
                        <a href="{% url 'website:cadastra_cliente' %}"
                           class="btn btn-primary">
                            Novo Cliente
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Lista de Clientes</h5>
                        <p class="card-text">
                            Veja aqui a lista de <code>Clientes</code> cadastrados.
                        </p>
                        <a href="{% url 'website:lista_clientes' %}"
                           class="btn btn-primary">
                            Vá para Lista
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

siscostura/website/templates/website/clientes/lista.html
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Clientes{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card border-dark" data-aos="fade-in" data-aos-duration="750">
                <div class="card-header"><b>Lista de Clientes</b></div>
                    <div class="card-body">
                        {% if clientes|length > 0 %}
                            <p class="card-text">Aqui está a lista de <code>Clientes</code> cadastrados.</p>

                            <form class="form-inline" action="{%url 'website:lista_clientes' %}" >
                                <div class="form-group mx-sm-3 mb-2">
                                    <input class="form-control" type="search" name="search">
                                    <br/>
                                    <button class="btn btn-primary" type="submit"> Buscar </button>
                                </div>
                            </form>

                            <table class="table table-light table-striped table-hover align-middle">
                                <thead>
                                <tr>
                                    <th scope="col"></th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Data nascimento</th>
                                    <th scope="col">CPF</th>
                                    <th scope="col">Telefone</th>
                                    <th scope="col" class="text-center">Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for cliente in clientes %}
                                    <tr>
                                        <th scope="row">{{ cliente.nome|primeira_letra }}</th>
                                        <td>{{ cliente.nome }}</td>
                                        <td>{{ cliente.data_nascimento }}</td>
                                        <td>{{ cliente.cpf }}</td>
                                        <td>{{ cliente.telefone }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'website:atualiza_cliente' pk=cliente.id %}"
                                               class="btn btn-primary btn-sm">
                                                Atualizar
                                            </a>
                                            <a href="{% url 'website:deleta_cliente' pk=cliente.id %}"
                                               class="btn btn-danger btn-sm">
                                                Excluir
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <div class="text-center mt-5 mb-5 jumbotron">
                                <h5>Nenhum <code>Cliente</code> cadastrado ainda.</h5>
                            </div>
                        {% endif %}
                        <hr/>
                        <div class="text-end">
                            <a href="{% url 'website:cadastra_cliente' %}" class="btn btn-primary btn-sm">
                                Cadastrar Cliente
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}