siscostura/siscostura/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [

    # Inclui as URLs do app website
    path('', include('website.urls', namespace='website')),
    # Adminstrativo
    path("admin/", admin.site.urls),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

siscostura/website/urls.py
# Importamos a função index() definida no arquivo views.py
from django.urls import path
from django.urls import include
from . import views
from .views import delete_item
from django.contrib.auth import views as auth_views

app_name = 'website'

# urlpatterns contém a lista de roteamentos de URLs
urlpatterns = [

    # GET /
    path('', views.HomeView.as_view(), name="index"),

    # GET /clientes
    path('clientes/', views.HomeClienteView.as_view(),
         name="index_clientes"),

    # GET /clientes/cadastrar
    path('clientes/cadastrar', views.CriaClienteView.as_view(),
         name="cadastra_cliente"),

    # GET /clientes
    path('clientes/lista', views.ListaclientesView.as_view(),
         name="lista_clientes"),

    # GET/POST /clientes/{pk}
    path('clientes/<pk>', views.AtualizaClienteView.as_view(),
         name="atualiza_cliente"),

    # GET/POST /clientes/excluir/{pk}
    path('clientes/excluir/<pk>',
         views.DeletaClienteView.as_view(), name="deleta_cliente"),


    # GET /pedidos
    path('pedidos/', views.HomePedidoView.as_view(),
         name="index_pedidos"),

    # GET /pedidos/cadastrar
    path('pedidos/cadastrar', views.CriaPedidoView.as_view(),
         name="cadastra_pedido"),

    # GET /pedidos
    path('pedidos/lista', views.ListaPedidoView.as_view(),
         name="lista_pedidos"),

    # GET/POST /pedidos/{pk}
    path('pedidos/<pk>', views.AtualizaPedidoView.as_view(),
         name="atualiza_pedido"),

    # GET/POST /clientes/excluir/{pk}
    path('pedidos/excluir/<pk>',
         views.DeletaPedidoView.as_view(), name="deleta_pedido"),

    path('delete-item/<int:pk>/', delete_item, name='delete_item'),

    #path('add-row/', views.add_row_pedido_items_hx, name='add_row_pedido_items_hx'),
     


]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),    
]

siscostura/website/forms.py
from siscostura.models import Cliente
from siscostura.models import Pedido
from siscostura.models import ItemPedido
from django import forms
from django.forms import inlineformset_factory

# FORMULÁRIO DE INCLUSÃO DE CLIENTES
# -------------------------------------------

class InsereClienteForm(forms.ModelForm):

    observacao = forms.CharField(
        label='Observação',
        required=False,
        widget=forms.Textarea
    )

    data_nascimento = forms.DateField(
        label='Data nascimento',
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    ESTADOS = (('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'),
               ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'))
    endereco_estado = forms.ChoiceField(choices=ESTADOS)

    class Meta:
        # Modelo base
        model = Cliente

        # Campos que estarão no form
        fields = [
            'nome',
            'data_nascimento',
            'cpf',
            'telefone',
            'endereco_logradouro',
            'endereco_numero',
            'endereco_complemento',
            'endereco_cep',
            'endereco_bairro',
            'endereco_cidade',
            'endereco_estado',
            'observacao',
        ]

# FORMULÁRIO DE INCLUSÃO DE PEDIDOS
# -------------------------------------------


class InserePedidoForm(forms.ModelForm):

    observacao = forms.CharField(
        label='Observação',
        required=False,
        widget=forms.Textarea
    )

    cliente = forms.ModelChoiceField(
        label='Cliente',        
        queryset=Cliente.objetos.all().order_by('nome'),
        required=True,
        
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    data_pedido = forms.DateField(
        label='Data pedido',
        required=False,
        widget=forms.DateInput(format='%d/%m/%Y')
    )

    class Meta:
        # Modelo base
        model = Pedido

        fields = '__all__'

class ItemPedidoForm(forms.ModelForm):
    class Meta:
        model = ItemPedido
        fields = '__all__'

ItemPedidoFormSet = inlineformset_factory(
    Pedido, ItemPedido, form=ItemPedidoForm,
    extra=1, can_delete=True,
    can_delete_extra=True
)

siscostura/website/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from siscostura.models import Cliente
from siscostura.models import Pedido
from .forms import InserePedidoForm
from django.urls import reverse_lazy
from .forms import InsereClienteForm
from django.urls import reverse_lazy
from .forms import ItemPedidoFormSet
from .forms import ItemPedidoForm
from siscostura.models import ItemPedido
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


# Create your views here.


# PÁGINA PRINCIPAL
# ----------------------------------------------


@method_decorator(login_required(login_url='accounts/login/'), name='dispatch')
class HomeView(TemplateView):
    template_name = "website/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data()

        return context


# PÁGINA PRINCIPAL CLIENTES
# ----------------------------------------------

class HomeClienteView(TemplateView):
    template_name = "website/clientes/index.html"


# LISTA DE CLIENTES
# ----------------------------------------------

class ListaclientesView(ListView):
    template_name = "website/clientes/lista.html"
    model = Cliente
    context_object_name = "clientes"


    def get_queryset(self):
        queryset = super().get_queryset()
        term = self.request.GET.get('search')

        print(term)
        if term:
            return queryset.filter(nome__icontains=term)
        return queryset


# CADASTRAMENTO DE CLIENTES
# ----------------------------------------------

class CriaClienteView(CreateView):
    template_name = "website/clientes/cria.html"
    model = Cliente
    form_class = InsereClienteForm
    success_url = reverse_lazy("website:lista_clientes")


# ATUALIZAÇÃO DE CLIENTES
# ----------------------------------------------

class AtualizaClienteView(UpdateView):
    template_name = "website/clientes/atualiza.html"
    model = Cliente
    fields = '__all__'
    context_object_name = 'Cliente'
    success_url = reverse_lazy("website:lista_clientes")


# EXCLUSÃO DE CLIENTES
# ----------------------------------------------

class DeletaClienteView(DeleteView):
    template_name = "website/clientes/exclui.html"
    model = Cliente
    context_object_name = 'Cliente'
    success_url = reverse_lazy("website:lista_clientes")


# PÁGINA PRINCIPAL PEDIDOS
# ----------------------------------------------

class HomePedidoView(TemplateView):
    template_name = "website/pedidos/index.html"

# LISTA DE PEDIDOS
# ----------------------------------------------


class ListaPedidoView(ListView):
    template_name = "website/pedidos/lista.html"
    model = Pedido
    context_object_name = "pedidos"


# CADASTRAMENTO DE PEDIDOS
# ----------------------------------------------
class PedidoInline():
    form_class = InserePedidoForm
    model = Pedido
    template_name = "website/pedidos/cria.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        self.object = form.save()
        

        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_items_pedido_valid', None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('/pedidos/lista')

    def formset_items_pedido_valid(self, formset):
        """
        Hook for custom formset saving.. useful if you have multiple formsets
        """
        items_pedido = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this, if you have can_delete=True parameter set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for item_pedido in items_pedido:
            item_pedido.pedido = self.object
            item_pedido.save()


class CriaPedidoView(PedidoInline,CreateView):
     
    def get_context_data(self, **kwargs):
        ctx = super(CriaPedidoView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'item_pedido': ItemPedidoFormSet(prefix='items'),                
            }
        else:
            return {
                'item_pedido': ItemPedidoFormSet(self.request.POST or None, self.request.FILES or None, prefix='items'),                
            }




# ATUALIZAÇÃO DE PEDIDOS
# ----------------------------------------------

class AtualizaPedidoView(PedidoInline,UpdateView):
   def get_context_data(self, **kwargs):
        ctx = super(AtualizaPedidoView, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx
   
   def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'items': ItemPedidoFormSet(prefix='items'),   
            }
        else:
            return {
                'items': ItemPedidoFormSet(self.request.POST or None, self.request.FILES or None, prefix='items'),                
            }


# EXCLUSÃO DE PEDIDOS
# ----------------------------------------------

class DeletaPedidoView(DeleteView):
    template_name = "website/pedidos/exclui.html"
    model = Pedido
    context_object_name = 'Pedido'
    success_url = reverse_lazy("website:lista_pedidos")

def delete_item(request, pk):
    try:
        itemPedido = ItemPedido.objetos.get(id=pk)
    except ItemPedido.DoesNotExist:
        messages.success(
            request, 'Objeto não encontrado'
            )
        return redirect('website:atualiza_pedido', pk=itemPedido.pedido.id)

siscostura/website/templates/website/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual%}

<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Title -->
    <title>{% block title %}Siscostura - Sistema de Gerenciamento de Corte e costura{% endblock %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'website/img/favicon.ico' %}" type="image/png">


    <!-- Arquivos CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/master.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/aos.css' %}">

    {% block styles %}{% endblock %}
</head>

<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">
            <h3 style="text-decoration: underline">SISCOSTURA</h3>
        </a>
        <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'website:index' %}">Página Inicial</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:lista_clientes' %}">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:lista_pedidos' %}">Pedidos</a>
                </li>
            </ul>
            <ul class="navbar-nav float-right">
                <li class="nav-item">

                </li>
            </ul>
        </div>
        {% endif %}

        <ul class="sidebar-nav" style="color: white">
            {% if user.is_authenticated %}
              <li>Usuário: {{ user.get_username }}</li>
              <li><a href="{% url 'logout'%}?next=/accounts/login">Logout</a></li>
            {% else %}
              <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div data-aos="fade-in" data-aos-duration="1000">
    <!-- Conteúdo do site -->
    {% block conteudo %}{% endblock %}
</div>

<!-- Scripts .js -->
<script src="{% static 'website/js/jquery.min.js' %}"></script>
<script src="{% static 'website/js/bootstrap.min.js' %}"></script>
<script src="{% static 'website/js/aos.js' %}"></script>

{% block scripts %}{% endblock %}

<script src="{% static 'website/js/scripts.js' %}"></script>

<script type="application/javascript">
    AOS.init();
</script>
</body>
</html>

siscostura/website/templates/website/_layouts/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">

  </ul>

  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>


   {% endif %}
  </ul>

   {% if user.is_staff %}
   <hr>
   <ul class="sidebar-nav">
   <li>Staff</li>
   {% if perms.catalog.can_mark_returned %}

   {% endif %}
   </ul>
    {% endif %}

{% endblock %}
  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}

  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}


  </div>
</div>

</div>
</body>
</html>